- name: Create ByParr container - takes long time
  community.docker.docker_container:
    name: byparr
    image: ghcr.io/thephaseless/byparr:main
    pull: true
    state: started
    restart_policy: unless-stopped
    init: true
    ports:
      - "8192:8191"
    
