---
username: "<username>"

docker_dir: /<PATH>/docker_apps
data_dir: /<PATH>/data
nvme_dir: /<PATH>/


puid: "<puid>"

pgid: "<pgid>"

ip_address: "<server_ip>"

timezone: "<timezone>"


packages:
  - unzip
  - wget
  - curl
  - git
  - python3
  - pip
  - smartmontools
  - python3-markdown 
  - jq
  - bc
  - python3-venv
  - fwupd
  - fastfetch
  
pip_packages:
  - ansible
  - github3.py
  - docker

docker_dependencies:
  - ca-certificates
  - gnupg
  - curl

docker_packages:
  - docker-ce
  - docker-ce-cli
  - containerd.io
  - docker-buildx-plugin
  - docker-compose-plugin

